# docker-compose run web rm -rf /myapp/tmp/pids/server.pid

version: "2"
services:
  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/redis/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Niri@123

  app:
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - 'docker.env'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  sidekiq:
    stdin_open: true
    build: .
    command: bundle exec sidekiq
    env_file:
      - 'docker.env'
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
